name: Django dia

on: [push]

jobs:
  build:
    strategy:
      matrix:
        include:
          - python: "3.9.13"
            django: ">=3.0,<4.0"

          - python: "3.10.5"
            django: ">=4.0,<5.0"

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install "Django${{ matrix.django }}"
          pip install -e .[tests]
      - name: Test with pytest
        run: |
          pytest -vv
